### ISSUE TITLE
Some landuse elements missing: village_green, allotments, playground

### ISSUE THREAD

**Issue by lenalebt** [protomaps/basemaps#204]
**Description**
OSM tagged areas with `landuse=village_green` and `landuse=allotments` are missing in the tileset. Same is true for polygons with `leisure=playground`. I think they should all be included in layer "landuse" with

- kind=village_green
- kind=allotments
- kind=playground

**Location**
https://www.openstreetmap.org/#map=18/51.50497/7.31888

**Screenshots**
![grafik](https://github.com/protomaps/basemaps/assets/697104/74ea2fb3-90b9-4a06-ac7a-eac2d833e8ab)
vs
![grafik](https://github.com/protomaps/basemaps/assets/697104/4f840826-438a-431d-9e8c-4abc7b0326c2)

I can provide a PR, if that helps :-)

**Comment by nvkelso** [comment]
Great suggestions! Yes, a PR is welcome :) Please update both landuse and POIs layers and include tests.

**Comment by bdon** [comment]
Thanks for the PR! We may want to show labels for these in the POIs layer using polylabel; in any case we need to make modifications to the style now to show these.

**Comment by bdon** [comment]
If you want your green areas to be labeled with text, generally we want to use the "polylabel" function in the Java code to find the pole of inaccessibility for a polygon, and then label it only using a point in the style. This is preferred over putting those properties in the polygon because they might cover multiple tiles and we only want a single label. Though if you have a specific instance in your style we can work from a visual and determine if this is really necessary.

**Comment by nvkelso** [comment]
@lenalebt Sorry I missed the originalquestion to me in the PR.

To add the labels to the POIs layer, edit this file to include the same tags you included in the Lanuse.java class in https://github.com/protomaps/basemaps/pull/206:

- https://github.com/protomaps/basemaps/blob/main/tiles/src/main/java/com/protomaps/basemap/layers/Pois.java

As to if the labels are appropriate, I generally fallback on the research done in Tilezen's equivalent logic:

- https://github.com/tilezen/vector-datasource/blob/master/yaml/pois.yaml

In this case YES for [allotments](https://github.com/tilezen/vector-datasource/blob/master/yaml/pois.yaml#L1258-L1266) (because community gardens often have names) but  NO for `village_green` (and YES for `playground`). 

Redoing the research for `village_green` using [TagInfo](https://taginfo.openstreetmap.org/tags/landuse=village_green#combinations) with current state of OSM data, I see that 4% of those features now have names. So if you wanted to add them up to you. The others are more than 10%.
