### ISSUE TITLE
More baselayers

### ISSUE THREAD

**Issue by pietervdvn** [protomaps/basemaps#224]
Hi,

Because I didn't like the colour scheme of 'protomaps.light', I'm in the process of creating a new one - partly inspired by Mapnik/Osm-carto, partly by MapTiler. You can already browse it at https://dev.mapcomplete.org/cyclofix.html? (ignore the pins)

It uses the current hosted version of protomaps.

Would this be considered a nice addition for protomaps? If so, please point me where this theme should be put, I'll open a PR then.

**Comment by bdon** [comment]
In general, no, themes beyond the base 5 (light, dark, white, grayscale, black) we can't commit to maintaining indefinitely into the future. 

The suggested theming approach is to create a set of named color variables like here https://github.com/protomaps/basemaps/blob/main/styles/src/themes.ts instead of writing a complete style, because that would let any color scheme take advantage of changes in the upstream style.

Otherwise you can suggest an improvement specific to what you don't like? Deriving things from OSM Carto is fine, but other styles will likely not be license-compatible with the styles in this repo.

**Comment by Edefritz** [comment]
Thanks for your suggestions about creating a theme instead of meddling with the styles themselves.

But as far as I can see, there is no way to pass a custom theme to any of the exported functions of the package. They basically only allow passing a key to existing themes:

```ts
export default function (source: string, key: string): LayerSpecification[] {
  const theme = themes[key];
  return nolabels_layers(source, theme).concat(labels_layers(source, theme));
}

export function noLabels(source: string, key: string): LayerSpecification[] {
  const theme = themes[key];
  return nolabels_layers(source, theme);
}

export function labels(source: string, key: string): LayerSpecification[] {
  const theme = themes[key];
  return labels_layers(source, theme);
}

```

I guess to do that we need something like this?

```ts
export function layersWithTheme(source: string, theme: Theme): LayerSpecification[] {
  return nolabels_layers(source, theme).concat(labels_layers(source, theme));
}
```

I'm happy to provide a PR if necessary. Or am I missing something?

**Comment by bdon** [comment]
@Edefritz yes, that looks like the right approach. It doesn't express a good way to separate labels/no labels for custom themes, or a way to inherit parts of a theme without re-defining every single theme property, but we can address those issues later. Can you open a PR?

**Comment by bdon** [comment]
I've gotten a lot of feedback wanting more custom styles, so I've created a repository for "3rd-party" styles here: 

https://github.com/protomaps/basemaps-themes

Each theme object should live in a separate `.ts` file like this: https://github.com/protomaps/basemaps-themes/blob/main/themes/bright.ts

The intention is to have a fairly open contribution policy on the `basemap-themes` repo: if your theme is sufficiently different from an existing one, and you make it available under a strictly permissive license, it should be accepted.
