### ISSUE TITLE
water layer: kind=ocean for zooms > 5 rather than changing to kind=water

### ISSUE THREAD

**Issue by dericke** [protomaps/basemaps#329]
**Description**
The value of `kind` for oceans switches from `ocean` at and below z5, to `water` at and above z6. I would find it really helpful if this could stay consistent across zoom levels. I was trying to extract just the oceans from the protomaps builds and mashup with a different data source for inland water, but I can't do this beyond z5 without an attribute to differentiate the oceans (in v4; in v3, I could use the presence of the `natural` key to do this). 

As a workaround, I'm going to try the polygons from [OSMData](https://osmdata.openstreetmap.de/data/water-polygons.html) as an ocean source, but it would be a great enhancement if this wasn't necessary. I can imagine other use cases where it would be helpful to differentiate oceans from inland water—someone might want different colors for each, for example.

[Example zoomed right before the changover](https://pmtiles.io/?url=https%3A%2F%2Fbuild.protomaps.com%2F20241104.pmtiles#map=5.83/36.861/-73.877)

**Comment by wipfli** [comment]
Interesting idea. Can you maybe open a pull request with the suggested changes?

**Comment by wipfli** [comment]
Thanks for the pull request. Since we are at it we might also want to have  a closer look at lakes and rivers I think.

Looking a bit at how things are at the moment we have here:

* Rhine river `kind=water`, `kind_detail=river` z15 [Link](https://pmtiles.io/?url=https%3A%2F%2Fbuild.protomaps.com%2F20241104.pmtiles#map=15.21/47.63784/8.609245)
* Lake Zurich `kind=lake`, `kind_detail=lake` z11 [Link](https://pmtiles.io/?url=https%3A%2F%2Fbuild.protomaps.com%2F20241104.pmtiles#map=11.93/47.26667/8.66643)
* Mediterranean `kind=water` z6 [Link](https://pmtiles.io/?url=https%3A%2F%2Fbuild.protomaps.com%2F20241104.pmtiles#map=6.3/41.839/6.808)
* Mediterranean `kind=ocean` z5 [Link](https://pmtiles.io/?url=https%3A%2F%2Fbuild.protomaps.com%2F20241104.pmtiles#map=5.16/42.631/8.99)

**Comment by wipfli** [comment]
Are you interested in making a proposal to harmonize those as well?

**Comment by dericke** [comment]
The lake and river examples appear to be compliant with the [Tilezen documentation](https://tilezen.readthedocs.io/en/latest/layers/), and I believe it's a goal of this project to stay close to Tilezen's structure. While `river` is listed as a potential value for `kind`, that's only for lines, not for polygons. 

My PR would bring things closer to the Tilezen spec, which says oceans have `kind=ocean` regardless of zoom level. I think changing how lakes and river polygons are tagged is probably worthy of a separate discussion, and I'm not sure I'm the best person to propose those changes.

**Comment by bdon** [comment]
Agree a separate PR would be welcome to harmonize non-oceans with the Tilezen implementation.
