### ISSUE TITLE
MaplibreGL broken river rendering

### ISSUE THREAD

**Issue by MightyPork** [protomaps/basemaps#373]
I opened the issue here https://github.com/maplibre/maplibre-gl-js/issues/4763 but maybe it is a bug in this repo instead. More details are in the other issue.

![Screenshot_20240925_123854](https://github.com/user-attachments/assets/39069141-25a4-476a-868c-7d554134472c)

the map file was grabbed today using this command:

```
pmtiles extract https://build.protomaps.com/20240924.pmtiles my_area.pmtiles --bbox=14.566343,50.150491,14.761007,50.243677
```

I get the same broken rendering with your example html file, completely unchanged outside of editing the source link and coordinates.

This bug does not reproduce with the example file https://pmtiles.io/protomaps(vector)ODbL_firenze.pmtiles

my pmtiles command line tool is installed from AUR, version 1.20.0

**Comment by bdon** [comment]
The style and tiles adhere to semantic versioning. They are not necessarily the same number version, for example:

Style v3 requires tileset v3
Style v4 requires tileset v4
Style v5 will require tileset v4

Did your roads disappearing happen because you were using a v3 style with tileset v4?

There is now a version checker as part of https://maps.protomaps.com which will warn you if there is a style/tileset compatibility mismatch. 

The current version is "stable" in so far as we stick to semantic versioning. We need to make breaking changes but in those cases the major version will increase.

**Comment by MightyPork** [comment]
Okay, I didn't notice the version column on the builds page, that makes sense.

The previous version was 20240924 as shown in the original post. It isn't listed on the builds website, possibly it was broken and you removed it?

**Comment by bdon** [comment]
I remove some of the builds but I keep at least one build for each semantic version. 20240924 would have been `4.0.0-alpha.4` which had some differences from `4.0.0`.

There are no immediate plans to have a tileset version 5, so the tileset should be stable for quite a while, though styles version 5 should be released soon.
